# this is the specific page

import streamlit as st
st.subheader("What did you set out to study? ")
st.write("The primary objective of this research project was to understand the impact of consumer ratings on the effectiveness of FDA-regulated drugs. I analyzed how factors such as 'Satisfaction' and 'Ease of Use' relate to the effectiveness ratings of drugs, providing a quantitative basis to assess consumer perceptions. Moreover, I also take drug price into account to determine whether the cost of drugs influences consumer perceptions of effectiveness, identifying if a higher price correlates with higher perceived effectiveness or vice versa. This research offer actionable insights for pharmaceutical companies to refine their product development and marketing strategies based on consumer feedback, potentially leading to improved user satisfaction and better market performance. In addition, it provides data-driven insights that could assist regulatory bodies in understanding consumer experiences, helping to shape policies that prioritize both efficacy and consumer satisfaction.")

st.subheader("What did you Discover/what were your conclusions")
st.write("The results of the study reveal that the linear regression model, which has been rigorously tested and found statistically significant, demonstrates that 'Satisfaction' and 'Ease of Use' are key determinants of a drug's perceived effectiveness. Notably, a rise of one unit in 'Ease of Use' corresponds to a 0.1502 unit increase in the drug's effectiveness score. In a similar vein, improving 'Satisfaction' by one unit results in a substantial 0.7141 unit enhancement in effectiveness. On the other hand, the analysis indicates that 'Price' does not significantly impact the effectiveness ratings, suggesting that cost may not be a primary factor in consumer evaluations of drug effectiveness. The research findings largely align with my initial hypotheses, albeit with some slight variations. I anticipated that the ratings of satisfaction and usability would correlate with drug effectiveness, and the results indeed confirmed this assumption. However, I also expected that the effectiveness would be influenced by the varying prices of drugs, but this turned out not to be statistically significant.")

st.subheader("What difficulties did you have in completing the project?")
st.write("On one hand, I found it extremely challenging to be creative and formulate a research question that was both interesting and feasible to analyze using the available datasets. This may be due to my limited knowledge of analytical techniques, which restricted me to building only linear regression models with my data. On the other hand, while I found coding the web app to be intriguing, it was also quite challenging. I aimed to create a more appealing and creative web interface, and although I consulted the Streamlit documentation extensively, it did not fully meet my expectations. I struggled to find additional resources or ideas that could help enhance the development of the web app.")

st.subheader("What skills did you wish you had while you were doing the project?")
st.write("I think an advanced statistical analysis skills, such as proficiency in machine learning techniques or time series analysis, would have allowed for deeper insights and more complex data interpretations. Also, the knowledge of front-end web development technologies such as Java would have been invaluable. This skill could have enabled me to customize the web app more extensively and achieve a higher level of interactivity and user experience.")

st.subheader("What would you do “next” to expand or augment the project?")
st.write("To expand and enhance this project, I would integrate additional diverse datasets, such as clinical trial results and real-world drug usage information, and employ advanced analytical techniques like machine learning and natural language processing to deepen the analysis. In addition, the most important thing is I will enhance the web application with more interactive dashboards and improved UI/UX design that would make it a more effective tool for hypothesis testing and user engagement.")


